### ISSUE TITLE
Please add source code

### ISSUE THREAD

**Issue by pcav** [lmotta/debug_vs_plugin#2]
it currently seems incomplete.

**Comment by jonnyforestGIS** [comment]
@pcav it's seems that the code is in init.py

The steps for put this plugin working are:
1.º Install pip dependency in QGIS3
2.º Run QGIS 3 and go to the plugin to enable the remote debugger
3.º Open Visual Studio Code and run in th Debbuger panel Python:attach.

@lmotta do you confirm this steps, i validate steps in my QGIS 3 version for Windows OS.

Regards,
João

**Comment by lmotta** [comment]
@jonnyforestGIS you're right.

The way the plugin works and its dependency are written in metadata.txt, this is shown when the user will install the plugin.

The plugin check if the ptvsd module exists, if not install, the plugin show the message "Need install ptvsd: pip3 install ptvsd".

Thanks for report and test in Windows.
